# Generated by Django 3.0.6 on 2020-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=120)),
                ('lname', models.CharField(max_length=80)),
                ('bio', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10000000)),
                ('title', models.TextField(default='Dentist')),
            ],
        ),
    ]
