# Generated by Django 3.0.6 on 2020-05-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='salary',
        ),
    ]
