# Generated by Django 3.0.6 on 2020-05-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20200525_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000000),
        ),
    ]
