# Generated by Django 3.0.6 on 2020-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
